Invalid Code

errordomain FooError {
	BAR
}

void main () {
	try {
	} catch (FooError err) {
	} catch (FooError err) {
	}
}
